package com.example.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "UserTable")
public class User {
	

	    
	    @DynamoDBHashKey(attributeName = "id")
	    @DynamoDBAutoGeneratedKey
	  private String id;
	    
	    @DynamoDBAttribute (attributeName = "name")
	  private String name;
	    
	    @DynamoDBAttribute (attributeName = "age")
	  private Integer age;
	    
	    @DynamoDBAttribute (attributeName = "email")
	  private String email;
	    
	    @DynamoDBAttribute (attributeName = "gender")
	  private String gender;
	 
	  
	 /* public User(String name2, Integer age2, String email2, String gender) {
		// TODO Auto-generated constructor stub
	}*/
	//@DynamoDBHashKey
	  //@DynamoDBAutoGeneratedKey
	  //@DynamoDBIndexRangeKey(globalSecondaryIndexName = "premiumIndex")
	  public String getId() {
			return id;
		}
		public void setId(String id) {
			this.id = id;
		}
		
		
	  @DynamoDBAttribute
	  public String getName() {
			return name;
	  }
	  
	  public void setName(String name) {
			this.name = name;
	  }
	  
	  @DynamoDBAttribute
	  public Integer getAge() {
			return age;
	  }
	  public void setAge(Integer age) {
			this.age = age;
	  }
	  
	  
	  @DynamoDBAttribute
	  public String getEmail() {
			return email;
	  }
	  public void setEmail(String email) {
			this.email = email;
	  }
	public String getGender() {
		return gender;
	}
	public void setGender(String gender) {
		this.gender = gender;
	}
	  
	  
	  
	
		
		
	  
		
}


//PRASHANT COMENT: Structure here is different from one at http://codeomitted.com/aws-dynamodb-springboot-tutorial/
	//there every fields has DB attribute mapping on top ot it (before getter setter)
